export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"; 
export const CLEAR_PRODUCTS = "CLEAR_PRODUCTS"

export const RETRIEVE_CATEGORIES = "RETRIEVE_CATEGORIES";

export const SET_SEARCH_KEY = "SEARCH"
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY"